export const translatesRu = {
  "header.links.home": "Главная",

  "button.ru": "Ру",
  "button.en": "Англ",
  "menu.button.characters": "Персонажи",
  "menu.button.books": "Книги",
  "menu.button.movie": "Фильмы",
  "home.text.greet": "Властелин колец приветствует тебя! Что тебя интересует?",
  "footer.adress": "Aдрес",
  "footer.contact": "Kонтакты",
  "characters.text.greet": "Приветствую тебя, мой друг. Выбери букву!",
  "not.letter": "Увы, на эту букву нет персонажа!",
  "header.logout": "Выйти из аккаунта",
  "header.login": "Зарегистрироваться",
  "header.user": "Пользователь",
  "translate.lang": "Язык",
  "menu.small": "Меню",
  "radio.option": "Категория",
  "radio.option.name": "Имя",
  "radio.option.race": "Раса",
  "search.characters": "Искать персонажа",
  "filter.no": "К сожалению нет персонажа с таким(ой)",
  "filter.name": " именем",
  "filter.race": " расой",
  "loginPage.login": "Имя пользователя",
  "loginPage.password": "Пароль",
  "loginPage.inputName": "Введите имя",
  "loginPage.inputPassword": "Введите пароль",
  "loginPage.title": "Регистрация",
  "loginPage.button": "Зарегистрировать",
};
