export const translatesEn = {
  "header.links.home": "Home",
  "button.ru": "Ru",
  "button.en": "En",
  "menu.button.characters": "Characters",
  "menu.button.books": "Books",
  "menu.button.movie": "Movie",
  "home.text.greet":
    "Welcome to the Lord of the rings! What are you interested in?",
  "footer.adress": "Adress",
  "footer.contact": "Contact",
  "characters.text.greet": "I greet you my friend. Choose a letter!",
  "not.letter": "Alas, there is no character for this letter!",
  "header.logout": "Logout",
  "header.login": "Login",
  "header.user": "User",
  "translate.lang": "Lang",
  "menu.small": "Menu",
  "radio.option": "Option",
  "radio.option.name": "Name",
  "radio.option.race": "Race",
  "search.characters": "Search characters",
  "filter.no": "Unfortunately there is no character with that",
  "filter.name": " name",
  "filter.race": " race",
  "loginPage.login": "Login",
  "loginPage.password": "Password",
  "loginPage.inputName": "input name",
  "loginPage.inputPassword": "input password",
  "loginPage.title": "Login",
  "loginPage.button": "Login",
};
